// This file was autogenerated by calcdeps.py
goog.addDependency("../../../closure-templates/javascript/soyutils.js", [], []);
goog.addDependency("../../../closure-templates/javascript/soyutils_usegoog.js", ['soy', 'soy.StringBuilder'], ['goog.dom', 'goog.dom.NodeType', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../../../closure-templates/javascript/examples/simple_generated_x-zz.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/features-usage.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/simple-usage.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/simple_generated_en.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/features_generated_x-zz.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/simple_generated.js", [], []);
goog.addDependency("../../../closure-templates/javascript/examples/features_generated_en.js", [], []);
goog.addDependency("../../../study/hello/hello.soy.js", ['example.templates'], ['soy', 'soy.StringBuilder']);
goog.addDependency("../../../study/hello/hello.js", ['example'], ['goog.dom', 'example.templates']);
